typography_spectrum: 0.06486653117462993
color:
  brandStrength: 0.26490462804213166
  lightness: 0.09957606648094952
  saturation: 0.20456775999628007
  rhythmicContrast: 0.23205465590581298
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.37459026789292693
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/110e55e7-abd0-4a34-bfbf-316db6f14519.jpg
name: Ambassadors of Style
navigation:
  - name: HOME
    url: 'http://aostyle.org'
    type: external
  - name: About Us
    id: b60fe398-9e00-4840-8787-a89596cb80f1
    type: content
title: The Ambassadors of Style
description: 'The baddest of the bad, the coolest of the cool'
