typography_spectrum: 0.3139874937478453
color:
  brandStrength: 0.26490462804213166
  lightness: 0.09957606648094952
  saturation: 0.20456775999628007
  rhythmicContrast: 0.23205465590581298
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.7402290226891637
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/110e55e7-abd0-4a34-bfbf-316db6f14519.jpg
name: Ambassadors of Style
navigation:
  - name: HOME
    url: 'http://aostyle.org'
    type: external
  - name: ABOUT
    url: 'http://aostyle.org/about'
    type: external
description: 'The baddest of the bad, the coolest of the cool'
